services:
  backend:
    build:
      context: ./backend
      target: dev
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
      - db_data:/data
    ports:
      - "4001:3001"
    environment:
      - NODE_ENV=development
      # Allow CORS from dev frontend port
      - ALLOWED_ORIGIN=http://localhost:3003
      # Optional: stabilize file watching inside container
      - CHOKIDAR_USEPOLLING=1
      # Persistence / DB (dev defaults)
      # Use a named volume for SQLite database persistence
      - PERSIST_TRANSCRIPTS=1
      - DB_URL=file:/data/dev.db
    restart: unless-stopped
    networks:
      - app
  frontend:
    build:
      context: ./frontend
      target: dev
      args:
        # Direct API calls to mapped backend port (browser -> host -> container)
        NEXT_PUBLIC_API_BASE: http://localhost:4001
    environment:
      # Direct API calls to mapped backend port (browser -> host -> container)
      - NEXT_PUBLIC_API_BASE=http://localhost:4001
      - NODE_ENV=development
      # Improve file watching on macOS/WSL
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    ports:
      - "3003:3000"
    restart: unless-stopped
    networks:
      - app
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "3080:8080"
    environment:
      # These make Adminer more permissive
      ADMINER_DEFAULT_SERVER: "sqlite"
      ADMINER_DESIGN: "nette"
    user: 1000:1000
    volumes:
      - db_data:/data
      - ./adminer_login-password-less.php:/var/www/html/plugins-enabled/login-password-less.php

networks:
  app:
    driver: bridge

volumes:
  db_data:
    driver: local
