version: "3.9"
services:
  backend:
    build:
      context: ./backend
      target: dev
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app/src:cached
      - ./backend/.env:/app/.env:ro
      - /app/node_modules
    ports:
      - "4001:3001"
    environment:
      - NODE_ENV=development
      # Optional: stabilize file watching inside container
      - CHOKIDAR_USEPOLLING=1
    restart: unless-stopped
    networks:
      - app
  frontend:
    build:
      context: ./frontend
      target: dev
      args:
        # Not required for dev stage build, but documented for clarity
        BACKEND_ORIGIN: http://backend:3001
    environment:
      # Frontend calls `/api` and rewrites to the backend container
      - NEXT_PUBLIC_API_BASE=/api
      - BACKEND_ORIGIN=http://backend:3001
      - NODE_ENV=development
      # Improve file watching on macOS/WSL
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    depends_on:
      - backend
    ports:
      - "3003:3000"
    restart: unless-stopped
    networks:
      - app

networks:
  app:
    driver: bridge
