version: "3.9"
services:
  backend:
    build:
      context: ./backend
      target: dev
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    ports:
      - "4001:3001"
    environment:
      - NODE_ENV=development
      # Allow CORS from dev frontend port
      - ALLOWED_ORIGIN=http://localhost:3003
      # Optional: stabilize file watching inside container
      - CHOKIDAR_USEPOLLING=1
      # Persistence / DB (dev defaults)
      # NOTE: The backend currently supports SQLite (file:...) only. Postgres service
      # is provided for future work, but persistence is disabled by default here to
      # avoid runtime errors. To enable persistence with SQLite, set
      # PERSIST_TRANSCRIPTS=1 and DB_URL=file:./backend/data/dev.db (see docs).
    restart: unless-stopped
    networks:
      - app
  frontend:
    build:
      context: ./frontend
      target: dev
      args:
        # Direct API calls to mapped backend port (browser -> host -> container)
        NEXT_PUBLIC_API_BASE: http://localhost:4001
    environment:
      # Direct API calls to mapped backend port (browser -> host -> container)
      - NEXT_PUBLIC_API_BASE=http://localhost:4001
      - NODE_ENV=development
      # Improve file watching on macOS/WSL
      - CHOKIDAR_USEPOLLING=1
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    ports:
      - "3003:3000"
    restart: unless-stopped
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  db_data:
    driver: local
