version: "3.9"
services:
  backend:
    build:
      context: ./backend
      args:
        INSTALL_PROD: "false"
    env_file:
      - ./backend/.env
    command: npm run dev
    volumes:
      - ./backend/src:/app/src:cached
      - ./backend/.env:/app/.env:ro
      - /app/node_modules
    ports:
      - "4001:3001"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - app
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_BASE: http://backend:3001
    environment:
      - NEXT_PUBLIC_API_BASE=http://backend:3001
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    depends_on:
      - backend
    ports:
      - "3003:3000"
    restart: unless-stopped
    networks:
      - app

networks:
  app:
    driver: bridge
