import { BaseProvider } from './baseProvider.js';
import { GeminiAdapter } from '../adapters/geminiAdapter.js';
import { logger } from '../../logger.js';
import { logUpstreamRequest, logUpstreamResponse, teeStreamWithPreview } from '../logging/upstreamLogger.js';
import { Readable } from 'node:stream';

function wrapStreamingResponse(response) {
  if (!response || !response.body) return response;
  if (typeof response.body.on === 'function') return response;

  const canConvert = typeof Readable?.fromWeb === 'function' && typeof response.body.getReader === 'function';
  if (!canConvert) return response;

  let nodeReadable;
  return new Proxy(response, {
    get(target, prop, receiver) {
      if (prop === 'body') {
        if (!nodeReadable) {
          nodeReadable = Readable.fromWeb(target.body);
        }
        return nodeReadable;
      }
      return Reflect.get(target, prop, receiver);
    },
  });
}

export class GeminiProvider extends BaseProvider {
  createAdapter() {
    return new GeminiAdapter({
      config: this.config,
      settings: this.settings,
      getDefaultModel: () => this.getDefaultModel(),
    });
  }

  get apiKey() {
    return this.settings?.apiKey
      || this.config?.providerConfig?.apiKey
      || this.config?.geminiApiKey
      || process.env.GEMINI_API_KEY;
  }

  get baseUrl() {
    return this.settings?.baseUrl
      || this.config?.providerConfig?.baseUrl
      || 'https://generativelanguage.googleapis.com/v1beta';
  }

  isConfigured() {
    return Boolean(this.apiKey);
  }

  async makeHttpRequest(translatedRequest) {
    const client = this.httpClient || globalThis.fetch;
    if (!client) {
      throw new Error('No HTTP client available for Gemini provider');
    }

    const model = translatedRequest.__model;
    const stream = translatedRequest.__stream;

    // Clean up internal flags
    const payload = { ...translatedRequest };
    delete payload.__model;
    delete payload.__stream;

    const method = stream ? 'streamGenerateContent' : 'generateContent';
    let url = `${this.baseUrl}/models/${model}:${method}?key=${this.apiKey}`;

    if (stream) {
      url += '&alt=sse';
    }

    const headers = {
      'Content-Type': 'application/json',
      ...this.defaultHeaders,
    };

    // Log upstream request
    try {
      logUpstreamRequest({ url, headers, body: payload });
    } catch (err) {
      logger.error('Failed to log upstream request:', err);
    }

    const response = await client(url, {
      method: 'POST',
      headers,
      body: JSON.stringify(payload),
    });

    // Log upstream response
    try {
      const responseHeaders = response.headers && typeof response.headers.entries === 'function'
        ? Object.fromEntries(response.headers.entries())
        : {};

      if (stream) {
        const wrappedResponse = wrapStreamingResponse(response);
        const { previewPromise, stream: loggedStream } = teeStreamWithPreview(wrappedResponse.body, {
          maxBytes: 128 * 1024,
          encoding: 'utf8',
        });

        previewPromise.then((preview) => {
          logUpstreamResponse({
            url,
            status: response.status,
            headers: responseHeaders,
            body: preview,
          });
        }).catch((err) => {
          logger.error('Failed to capture streaming response preview:', err);
        });

        return new Proxy(wrappedResponse, {
          get(target, prop, receiver) {
            if (prop === 'body') {
              return loggedStream;
            }
            return Reflect.get(target, prop, receiver);
          },
        });
      } else {
        if (response.clone) {
          const clone = response.clone();
          const text = await clone.text();
          logUpstreamResponse({
            url,
            status: response.status,
            headers: responseHeaders,
            body: text,
          });
        }
        return response;
      }
    } catch (err) {
      logger.error('Failed to log upstream response:', err);
      return response;
    }
  }

  getToolsetSpec(_toolRegistry) {
    // Gemini tool specs are generated by the adapter during translation
    // We don't need to expose them separately here unless the registry needs it
    return [];
  }

  supportsTools() {
    return true;
  }

  supportsReasoningControls(_model) {
    return false;
  }

  supportsPromptCaching() {
    // Gemini supports context caching but it's a different API (cache manager)
    // For per-request caching via messages, it's not the same as Anthropic
    return false;
  }

  getDefaultModel() {
    return this.settings?.defaultModel
      || this.config?.defaultModel
      || 'gemini-1.5-flash';
  }
}
